### ISSUE TITLE
ARCHITECTURES_2_TASK is limiting the tasks able to be deployed with HF DLC

### ISSUE THREAD

**Issue by gwang111** [aws/sagemaker-huggingface-inference-toolkit#112]
## Issue:
Customer is deploying HF ID: `BAAI/bge-m3` with Task: `sentence-similarity` using:
```
model_builder = ModelBuilder(
    model=“BAAI/bge-m3”,
    schema_builder=SchemaBuilder(sample_input, sample_output),
    model_path=path, #local path where artifacts will be saved
    mode=Mode.LOCAL_CONTAINER,
    env_vars={
        "HF_TASK": "sentence-similarity"
    }
)

model_builder.deploy()
```

But getting the following from within the HF DLC:
```
ModelBuilder: DEBUG:     2024-02-13 00:05:57,567 [INFO ] W-BAAI__bge-m3-58-stdout 
com.amazonaws.ml.mms.wlm.WorkerLifeCycle - ValueError: Task couldn't be inferenced from XLMRobertaModel.Inference Toolkit 
can only inference tasks from architectures ending with ['TapasForQuestionAnswering', 'ForQuestionAnswering', 
'ForTokenClassification', 'ForSequenceClassification', 'ForMultipleChoice', 'ForMaskedLM', 'ForCausalLM', 
'ForConditionalGeneration', 'MTModel', 'EncoderDecoderModel', 'GPT2LMHeadModel', 'T5WithLMHeadModel'].Use env
`HF_TASK` to define your task.
```

## Root Cause:
`ARCHITECTURES_2_TASK` mapping is too constraining and does not include all admissible pipeline tasks:
https://github.com/aws/sagemaker-huggingface-inference-toolkit/blob/80634b30703e8e9525db8b7128b05f713f42f9dc/src/sagemaker_huggingface_inference_toolkit/transformers_utils.py#L79

All we do is pass the task to `get_pipeline` from within the `handler_service.py` as far as I can see: https://github.com/aws/sagemaker-huggingface-inference-toolkit/blob/80634b30703e8e9525db8b7128b05f713f42f9dc/src/sagemaker_huggingface_inference_toolkit/handler_service.py#L115

Shouldn't the logic be the following?:
```
if "HF_TASK" provided -> set task to "HF_TASK"

else:
    fetch architecture from config.json
    if architecture is not in ARCHITECTURES_2_TASK -> throw error
    set task to mapped task
```
This way we allow for a best effort deployment / a.k.a pass through for the HF_TASK to `get_pipeline()`. If that fails, then so be it we should propagate the right error messaging to the customer stating that we tried the best and that xyz went wrong.

**Comment by philschmid** [comment]
Hello,
task `sentence-similarity` is `sentence-transformers` specific which is not yet supported.

**Comment by mohanasudhan** [comment]
@philschmid  Is there a reason why we do not support all the tasks?

**Comment by gwang111** [comment]
ack so will this eventually be supported via `get_pipeline`? Or will it only be limited to:

```
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("BAAI/bge-m3")
```

**Comment by philschmid** [comment]
We might for on that in the future but for now the simplest is to create a inference.py, see here https://www.philschmid.de/custom-inference-huggingface-sagemaker

**Comment by philschmid** [comment]
> @philschmid there are a number of multimodal tasks missing here (object detection, text to speech, audio classification etc.)

Where is "here"? 

> Is there a way to extend this map further for new use-cases? This will also save customer effort to create the inference.py for these formats.

What map?

**Comment by samruds** [comment]
> > @philschmid there are a number of multimodal tasks missing here (object detection, text to speech, audio classification etc.)
> 
> Where is "here"?
> ARCHITECTURES_2_TASK https://github.com/aws/sagemaker-huggingface-inference-toolkit/blob/80634b30703e8e9525db8b7128b05f713f42f9dc/src/sagemaker_huggingface_inference_toolkit/transformers_utils.py#L79-L93


> > Is there a way to extend this map further for new use-cases? This will also save customer effort to create the inference.py for these formats.
> 
> What map? 
> ARCHITECTURES_2_TASK

**Comment by philschmid** [comment]
The `ARCHITECTURES_2_TASK` Is not actively used since its not longer always possible to derive the task from a model since the same "architecture" can have multiple tasks. Thats why we always (every example, guide, docs etc.) set the `TASK`.

**Comment by samruds** [comment]
There are two things here

1. Tasks being restricted by old implementation - fix is out for that.
2. Some transformers don't have tasks that have been exposed via pipeline tag yet - the option you provided is one solution (another could them be exposed as pipeline tag on a release cycle). I think we would need a list of libraries that do need custom inference to prioritize such an implementation. If custom inference is needed, is this the long term plan for such tasks. This looks to be more as a problem of supporting tasks in extremely nascent stage of development.

**Comment by samruds** [comment]
Customer has two options here

1. Set the HF task via env variables
2.  Provide inference.py for non task models like sentence similarity.
