### ISSUE TITLE
What if I want to bring more than an inference.py?

### ISSUE THREAD

**Issue by la-cruche** [aws/sagemaker-huggingface-inference-toolkit#12]
Hi,

I see in the docs that I can customize inference with an `inference.py` script. But what if I need more than that?

1. In particular, is it possible to bring a directory of scripts?
2. Is it possible to choose a custom entrypoint name or it has to be named inference.py?

**Comment by vdantu** [comment]
You should be able to bring in all your dependencies in the same model artifact. The `model_fn` is given `model_dir`. You could access any file/files in that folder. 

The entrypoint name can also be changed. Similar to PT inference toolkit, you would have to export ["`SAGEMAKER_PROGRAM=your_script.py`"](https://github.com/aws/sagemaker-inference-toolkit/blob/master/src/sagemaker_inference/parameters.py#L18).. Only catch is that "`your_script.py`" should be in "`PYTHONPATH`" and by default the "code" folder inside the model artifact is a part of PYTHONPATH.

**Comment by la-cruche** [comment]
perfect thanks @vdantu feel free to close
