### ISSUE TITLE
References on transformer 4.4 and pytorch 1.6 but image version no longer exists on ECR

### ISSUE THREAD

**Issue by benhyy** [aws/sagemaker-huggingface-inference-toolkit#14]
Instructions on https://github.com/aws/sagemaker-huggingface-inference-toolkit suggests the following:

```
# create Hugging Face Model Class
huggingface_model = HuggingFaceModel(
    transformers_version='4.4',
    pytorch_version='1.6',
    env=hub,
    role=role,
    name=hub['HF_MODEL_ID'], 
)
```

However it comes back with "The image '763104351884.dkr.ecr.us-east-1.amazonaws.com/huggingface-pytorch-inference:1.7.1-transformers4.4-gpu-py36-cu110-ubuntu18.04' does not exist.."

I found this blog that references a different transformer and pytorch version:
https://aws.amazon.com/blogs/machine-learning/announcing-managed-inference-for-hugging-face-models-in-amazon-sagemaker/
```
# create Hugging Face Model Class
huggingface_model = HuggingFaceModel(
   model_data="s3://bucket/model.tar.gz", # S3 path to your trained sagemaker model
   role=<SageMaker Role>, # IAM role with permissions to create an Endpoint
   transformers_version="4.6", # transformers version used
   pytorch_version="1.7", # pytorch version used
   py_version="py36", # python version of the DLC
)
```
Could you update this repo to prevent further confusion?

**Comment by philschmid** [comment]
can be closed @vdantu
