### ISSUE TITLE
Any plans for inference acceleration support?

### ISSUE THREAD

**Issue by tgjorgoski** [aws/sagemaker-huggingface-inference-toolkit#19]
I tried

```
predictor = huggingface_model.deploy(
    initial_instance_count=1,
    instance_type="ml.t2.medium",
    accelerator_type="ml.eia2.medium",
    endpoint_name=endpoint_name,
)
```

And got ``sagemaker Unsupported image scope: eia. You may need to upgrade your SDK version (pip install -U sagemaker) for newer image scopes. Supported image scope(s): training, inference.``

**Comment by philschmid** [comment]
Hey @tgjorgoski,
Yes, currently there are no EI compatible Inference DLCs. We are trying to make them available as soon as possible. The first version might not support the `zero-code` deployment we have with the default inference DLC.

**Comment by tyler-ground** [comment]
Any recent changes to support here?
