### ISSUE TITLE
batch transform can not find custom inference.py

### ISSUE THREAD

**Issue by BaoshengHeTR** [aws/sagemaker-huggingface-inference-toolkit#23]
Here is my problem. Does `Sagemaker-huggingface-inference-toolkit` support batch transform?  I created a `FrameworkModel` loading a trained model saved on S3 as (since `HuggingFaceModel` is not  available for `Sagemaker: 2.39.0`, so I use `FrameworkModel` here):

```
model = FrameworkModel(
    model_data=model_url,
    image_uri=image_uri,
    role=role,
    entry_point='inference.py', 
    name=name,
    vpc_config={
        'Subnets': vpc_subnets,
        'SecurityGroupIds': vpc_sgs        
    },
    source_dir='./source',
    sagemaker_session=Session(boto_session=boto3_session, default_bucket=s3_bucket),
)

transformer = model.transformer(
    tags=tags,
    instance_count=1,
    instance_type='ml.g4dn.xlarge',
    assemble_with='Line',
    output_path=predict_output_path,
    accept='application/jsonlines'
)

transformer.transform(
    data=input_path,
    content_type='application/jsonlines',
    split_type='Line',
    join_source= "Input",
)
```
Return error message:

`2021-07-23 04:04:25,545 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - sagemaker_inference.errors.UnsupportedFormatError: Content type application/jsonlines is not supported by this framework.`

However, such a content_type is handled in the `inference.py`. So I assume that this script is not loaded during the batch transform. Please help.

**Comment by philschmid** [comment]
Hey @BaoshengHeTR, 
`HuggingFaceModel` got introduced with `sagemaker>=2.48.0`. 

Could you change the `content_type` and `accept` to `application/json` ? 
We ran some tests using this snippet and with worked. 

```python
batch_job = huggingface_estimator.transformer(
    instance_count=1,
    instance_type='ml.c5.2xlarge',
    strategy='SingleRecord')
batch_job.transform(
    data='s3://sagemaker-us-west-2-579164220517/hf-batch-test/',
    content_type='application/json',    
    split_type='Line')
```

data sample: 
```csv
{"inputs":"this movie is terrible"}
{"inputs":"this movie is amazing"}
{"inputs":"SageMaker is pretty cool"}
{"inputs":"SageMaker is pretty cool"}
{"inputs":"this movie is terrible"}
{"inputs":"this movie is amazing"}
{"inputs":"SageMaker is pretty cool"}
{"inputs":"SageMaker is pretty cool"}
{"inputs":"this movie is terrible"}
{"inputs":"this movie is amazing"}
{"inputs":"SageMaker is pretty cool"}
{"inputs":"SageMaker is pretty cool"}
```

**Comment by BaoshengHeTR** [comment]
> Hey @BaoshengHeTR,
> `HuggingFaceModel` got introduced with `sagemaker>=2.48.0`.
> 
> Could you change the `content_type` and `accept` to `application/json` ?
> We ran some tests using this snippet and with worked.
> 
> ```python
> batch_job = huggingface_estimator.transformer(
>     instance_count=1,
>     instance_type='ml.c5.2xlarge',
>     strategy='SingleRecord')
> batch_job.transform(
>     data='s3://sagemaker-us-west-2-579164220517/hf-batch-test/',
>     content_type='application/json',    
>     split_type='Line')
> ```
> 
> data sample:
> 
> ```
> {"inputs":"this movie is terrible"}
> {"inputs":"this movie is amazing"}
> {"inputs":"SageMaker is pretty cool"}
> {"inputs":"SageMaker is pretty cool"}
> {"inputs":"this movie is terrible"}
> {"inputs":"this movie is amazing"}
> {"inputs":"SageMaker is pretty cool"}
> {"inputs":"SageMaker is pretty cool"}
> {"inputs":"this movie is terrible"}
> {"inputs":"this movie is amazing"}
> {"inputs":"SageMaker is pretty cool"}
> {"inputs":"SageMaker is pretty cool"}
> ```

Not work. The problem here is for batch transform, my own src `inference.py` is not loaded. You just gave the example to use internal apis.

**Comment by BaoshengHeTR** [comment]
to create the  model, the `model.tar.gz` file used as the `model_data` has the structure:

```
model.tar.gz/
|- model.pth
|- code/
  |- inference.py
```

**Comment by philschmid** [comment]
Hey @BaoshengHeTR, 


Could you try creating the `archive` with the following steps? 


1. go into custom code directory
```bash
cd {my-model-and-inference-code}
```

2. Create a tar file
```bash
tar zcvf model.tar.gz *
```

3. Upload model.tar.gz to s3
```bash
aws s3 cp model.tar.gz <s3://mymodel>
```
---

Btw. Why are you using a `model.pth`? and not the `transformers` saved files? Also, are `model.pth` and `infernece.py` the only files you include?

**Comment by BaoshengHeTR** [comment]
> Hey @BaoshengHeTR,
> 
> Could you try creating the `archive` with the following steps?
> 
> 1. go into custom code directory
> 
> ```shell
> cd {my-model-and-inference-code}
> ```
> 
> 1. Create a tar file
> 
> ```shell
> tar zcvf model.tar.gz *
> ```
> 
> 1. Upload model.tar.gz to s3
> 
> ```shell
> aws s3 cp model.tar.gz <s3://mymodel>
> ```
> 
> Btw. Why are you using a `model.pth`? and not the `transformers` saved files? Also, are `model.pth` and `infernece.py` the only files you include?

Thanks. I figured out what is going wrong. The `model.tar.gz` has to contain the code, and I have to include a loncal entrypoint in a  local `source_dir` as well. This is confusing because noboday could realize that the script has to be provided in both ways. Hope AWS could update the document or better fix this feature.

**Comment by philschmid** [comment]
@BaoshengHeTR we added this to the Hugging Face Documentation here https://huggingface.co/docs/sagemaker/inference#creating-a-model-artifact-modeltargz-for-deployment
