### ISSUE TITLE
how to deploy https://huggingface.co/flair/ner-english-ontonotes-large as it doesn't have a config.json

### ISSUE THREAD

**Issue by DevBey** [aws/sagemaker-huggingface-inference-toolkit#26]
Hi I was trying to deploy this model on sagemaker and unfortunately it throws an error because it can't find the config.json, I was able to deploy other models using the same template provided but this one failed because there is no config.json provided. the model is available for inference in the hugging face models API and it's working fine, so please let me know how can I deploy this model onto sagemaker !! https://huggingface.co/flair/ner-english-ontonotes-large

**Comment by philschmid** [comment]
Hey @DevBey, 

Currently, the SageMaker Hugging Face Inference Toolkit only supports `transformers` compatible models. That's also the reason why you don't see the option "Amazon SageMaker" on the model card. 

You can try to use the https://huggingface.co/asahi417/tner-xlm-roberta-large-ontonotes5 if you want a transformer-based fine-tuned on ontonotes

**Comment by DevBey** [comment]
yeah, that's what I understood too, but can we override the methods using inference.py. because all it needs is changes in just load model and predict methods ?? if this works I could also deploy KEYBERT which again is not natively available in transformers !! 

Though anyway currently I was able to deploy keybert and flair transformers onto sagemaker  by overriding their model loading and predicting functions !!

Do let me know if that would work, as I can see how optimized the hugging face sagemaker inference containers are compared to container deployed using mlflow !!

**Comment by philschmid** [comment]
Yes, you could create your own `inference.py` and adding a `requirements.txt` with your required dependencies. As documented here: https://huggingface.co/docs/sagemaker/inference#user-defined-codemodules

Would love to hear if you see some performance difference between the containers of mlflow. But I have to that we created them to run the Hugging Face libraries, so I am not sure if you see any improvements when using flair.

**Comment by DevBey** [comment]
ok great, thanks anyway for the help.

let me close this, for now.

only one more thing is there someplace I can find examples of custom inference.py, it would be great to see some examples of custom inference.py in PyTorch.

**Comment by philschmid** [comment]
Okay, closing this for now. Feel free to re-open it again. 

To your question, yes. The Documentation contains an example of how you can create a customer `inference.py` additionally you can take a look [here](https://github.com/aws/sagemaker-huggingface-inference-toolkit/blob/main/tests/resources/model_input_predict_output_fn/code/inference.py), that's the `inference.py` to run tests
