### ISSUE TITLE
pipeline parameters not read by the deployed endpoint

### ISSUE THREAD

**Issue by ruisi-su** [aws/sagemaker-huggingface-inference-toolkit#37]
Hi,

I followed the documentation in [https://huggingface.co/docs/sagemaker/inference](here) to setup an endpoint hosting a sentiment analysis model. However, when passed in `inputs` larger than 512, it now breaks:
```
line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (400) from primary with message "{
  "code": 400,
  "type": "InternalServerException",
  "message": "index out of range in self"
}
```

Setup code:
```
hub = {
    "HF_MODEL_ID": "distilbert-base-uncased",
    "HF_TASK": "sentiment-analysis",
}
huggingface_model = HuggingFaceModel(
    env=hub,  # configuration for loading model from Hub
    role=role,  # iam role with permissions to create an Endpoint
    transformers_version="4.6.1",  # transformers version used
    pytorch_version="1.7.1",  # pytorch version used
    py_version="py36",  # python version used
)
huggingface_model.deploy(initial_instance_count=1, instance_type="ml.m5.xlarge")
```
Invoking endpoint using this data:
```
data = {
    "parameters": {
        "return_all_scores": True,
        "truncation": "longest_first",
    },
    "inputs": "My Name is Philipp and I live in Nuremberg. "*300,
}
```

The same setup directly with Pipeline in the transformers API works perfectly fine:
```
model_name = "distilbert-base-uncased"
pipe = pipeline("sentiment-analysis", model=model_name, tokenizer=model_name)
data = {
    "parameters": {
        "return_all_scores": True,
        "truncation": "longest_first",
    },
    "inputs": "My Name is Philipp and I live in Nuremberg. "*300,
}

params = data.pop("parameters", None)
results = pipe(data["inputs"], **params)
```
where `print(results)` gives `[{'label': 'LABEL_1', 'score': 0.5471687912940979}]`

What is possibly wrong here? Could it be the toolkit version loaded by `HuggingFaceModel`?
> verified that the endpoint is run with the following versions `transformers=4.6.1, tokenizers=0.10.3, sagemaker=2.68.0`

**Comment by philschmid** [comment]
Hello @ruisi-su, 

The Toolkit is not automatically truncating your input. You either need to truncate your input on the client-side or you need to provide the `truncate` parameter in your request. 
```python
{
  'inputs': my_input,
  "parameters": {'truncation': True}
}
```

**Comment by ruisi-su** [comment]
@philschmid Thanks for the feedback. I did put `truncation` in my request before invoking the endpoint, as shown in the previous comment:
```
data = {
    "parameters": {
        "return_all_scores": True,
        **"truncation": "longest_first",**
    },
    "inputs": "My Name is Philipp and I live in Nuremberg. "*300,
}
```

**Comment by philschmid** [comment]
@ruisi-su could you try `True` for truncation. Not sure if and how "longest_first" works for a single input for the `pipelines`.

**Comment by ruisi-su** [comment]
@philschmid tried that as well, and it does not appear to work. Looks like `distilbert-base-uncased` does not have `truncation: True` in the [config.json](https://huggingface.co/distilbert-base-uncased/blob/main/tokenizer_config.json).

**Comment by ruisi-su** [comment]
I found the issue. I did not send the `tokenizer` to the `trainer` object. So the training job never saved the tokenizer.
```
    trainer = Trainer(
        model=model,
        tokenizer=tokenizer, <-- this was missing
        args=training_args,
        compute_metrics=compute_metrics,
        train_dataset=train_dataset,
        eval_dataset=test_dataset,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=3)],
    )
```
After training was properly setup, batch transform/deployment will work with the following data:
```
data = {"inputs": <some_long_text>*20, "parameters": {"truncation": True, "max_length": 512}}
```
I missed out reading this line`Note: Make sure your inputs fit the max_length of the model during preprocessing.` from the [https://huggingface.co/docs/sagemaker/inference#run-batch-transform-with-%F0%9F%A4%97-transformers-and-sagemaker](document)
