### ISSUE TITLE
Accessing context available to the handler in a custom model_fn

### ISSUE THREAD

**Issue by dlesomewhere** [aws/sagemaker-huggingface-inference-toolkit#40]
The default `load` function in the `HuggingFaceHandlerService` uses available context to set the device to `self.device` e.g.

```
if "HF_TASK" in os.environ:
    hf_pipeline = get_pipeline(task=os.environ["HF_TASK"], model_dir=model_dir, device=self.device)
```

When we override the `load` function from local storage our custom `model_fn` is not bound to the instance of `HuggingFaceHandlerService` so does not have access to useful local context e.g. `self.device`.  This makes it difficult to set the device for our custom pipeline.

Using `types.MethodType` to bind the custom `model_fn` would solve this problem and allow us to access context available to the handler when initializing our pipeline.

**Comment by dlesomewhere** [comment]
Hey @philschmid - I've submitted a PR to attempt to address this issue: https://github.com/aws/sagemaker-huggingface-inference-toolkit/pull/41.

I'd be interested to get your thoughts on this issue and the proposed change.

Cheers!

**Comment by philschmid** [comment]
Hey @dlesomewhere, 

I took a look and responded to it.
Why do you need access to `self.device` when creating a custom `model_fn` function anyways?
MMS which is used as an inference webservice will only start 1 worker when a GPU is available, which means that you can use `device=0` or [torch.cuda](https://pytorch.org/docs/stable/cuda.html)

**Comment by dlesomewhere** [comment]
Thanks @philschmid - it wasn't clear to us that `device=0` would always be correct but glad to hear it is so!

Also thanks for responding to my PR related to this issue.  I have closed it now, and will also close this issue.
