### ISSUE TITLE
Serverless Inference

### ISSUE THREAD

**Issue by navidre** [aws/sagemaker-huggingface-inference-toolkit#53]
Hello, and thank you for the open-source code. Does this code support serverless inference on AWS SageMaker as described [here](https://aws.amazon.com/about-aws/whats-new/2021/12/amazon-sagemaker-serverless-inference/)?

**Comment by philschmid** [comment]
Yes, it does. 
I wrote a blog post on how to easily use it with `cdk`: https://www.philschmid.de/serverless-transformers-sagemaker-huggingface
And Julien Simon also created a video on it: https://www.youtube.com/watch?v=cUhDLoBH80o&t=13s&ab_channel=JulienSimon

I hope this helps you getting started.

**Comment by philschmid** [comment]
We are going to add Documentation & more examples when the feature is out of preview
