### ISSUE TITLE
How should we name custom inference functions if providing a custom inference script?

### ISSUE THREAD

**Issue by la-cruche** [aws/sagemaker-huggingface-inference-toolkit#6]
Hi,

I see that the `HuggingFaceHandlerService` [uses](https://github.com/aws/sagemaker-huggingface-inference-toolkit/blob/a3e85a1670ca10fb4055932afa5dcba8fe02589e/src/sagemaker_huggingface_inference_toolkit/handler_service.py#L127) `load`, `preprocess`, `predict` and `postprocess` functions. The [doc](https://github.com/aws/sagemaker-huggingface-inference-toolkit#-user-defined-codemodules) mentions that custom `inference.py` scripts should use functions named `load_fn`, `preprocess_fn`, `predict`, `postprocess`. It's ok that the names are inconsistent within and across docs? We need `_fn` suffixes or not? or that's a typo in the doc?

**Comment by philschmid** [comment]
There is a PR for this already, which will be merged today. https://github.com/aws/sagemaker-huggingface-inference-toolkit/pull/2 
The `HuggingFaceHandlerService` itself is oriented at `torchserve`, `mms` & `kfserving` handlers. With the [PR](https://github.com/aws/sagemaker-huggingface-inference-toolkit/pull/2) we are unifying the custom modules to meet the SageMaker standards and best practices

**Comment by la-cruche** [comment]
alrighty but then what will be the contract to follow in the `inference.py`?

1. `load`, `preprocess`, `predict`, `postprocess` (what's in the default handler)
2. or `load_fn`, `preprocess_fn`, `predict`, `postprocess` (what's currently in the doc)
3. or `load_fn`, `preprocess_fn`, `predict_fn`, `postprocess_fn`

**Comment by philschmid** [comment]
The contract for customer, for custom modules in `inference.py` will be the same as for all other inference toolkits.
`model_fn`, `input_fn`, `predict_fn`, `output_fn` or `transform_fn`. If you take a look at the [PR](https://github.com/aws/sagemaker-huggingface-inference-toolkit/pull/2). It includes also the documentation changes. https://github.com/aws/sagemaker-huggingface-inference-toolkit/blob/6c0cdcb3be743c3ae89368473db0333d20a16a71/README.md#-user-defined-codemodules
