### ISSUE TITLE
Serverless inference using the Sagemaker toolkit

### ISSUE THREAD

**Issue by arnaudstiegler** [aws/sagemaker-huggingface-inference-toolkit#63]
Hey!
I was looking at how you've built this inference toolkit to try and figure out how to couple using the `Multi-Model-Service` package with serverless inference. I've seen that you coded your own `start_model_server` and your own service handler, I'd be super interested to hear whether any of the changes are related to using serverless inference endpoints. Thank you!

**Comment by philschmid** [comment]
SageMaker Platform features like Serverless Inference are not directly built into the toolkit. For Multimodel it should be the same except that we make sure the if a `inference.py` is provided it is used.

**Comment by arnaudstiegler** [comment]
They do mention that private registries are not supported, but they also specifically say that custom containers are supported (in the `Container Support` section). And the serverless endpoint starts, so I think it's only really a code issue with the sagemaker-inference default webserver

**Comment by arnaudstiegler** [comment]
Oh I actually found an answer [there](https://docs.aws.amazon.com/sagemaker/latest/dg/serverless-endpoints-troubleshooting.html).
Thanks for your answers!
