### ISSUE TITLE
How do I use my own config.properties

### ISSUE THREAD

**Issue by aj2622** [aws/sagemaker-huggingface-inference-toolkit#65]
How can I use my own config.properties
with the aws deep learning inference images (eg: `763104351884.dkr.ecr.us-east-1.amazonaws.com/huggingface-pytorch-inference:1.10.2-transformers4.17.0-gpu-py38-cu113-ubuntu20.04`) built on top on this tool kit

**Comment by aj2622** [comment]
I was trying to do something like this https://pytorch.org/serve/configuration.html. But I am realizing that hugging face images don't use torch server. 🤦 and that these options might not be available

**Comment by philschmid** [comment]
The Toolkit is based on [MMS](https://github.com/awslabs/multi-model-server). To provide your own `config.properties` you have to derive the container. You can find the currently used config here: https://github.com/aws/deep-learning-containers/blob/master/huggingface/build_artifacts/inference/config.properties
