### ISSUE TITLE
Where should we store config.json?

### ISSUE THREAD

**Issue by la-cruche** [aws/sagemaker-huggingface-inference-toolkit#9]
Hi,

I'm deploying the following artifact to SM HF Hosting

```
model.tar.gz
    code/
        inference.py
    squad_tf/
        config.json
        tf_model.h5
    squad_tf_tokenizer/
        special_tokens_map.json
        tokenizer.json
        tokenizer_config.json
        vocab.txt
```

When I send inferences I have errors in my logs, including file `/.sagemaker/mms/models/model/config.json not found` Where should that `config.json` be?

**Comment by philschmid** [comment]
Thats because your structure is not correct. It need to be 
```bash
model.tar.gz
    code/
        inference.py
    config.json
    tf_model.h5
    special_tokens_map.json
    tokenizer.json
    tokenizer_config.json
    vocab.txt
```
You can take a look [here](https://github.com/aws/sagemaker-huggingface-inference-toolkit#-user-defined-codemodules)

**Comment by la-cruche** [comment]
ok nice! we should write that in the doc no? to have all model artifacts directly in the archive without folder hierarchy

**Comment by philschmid** [comment]
It is actually documented [here](https://github.com/aws/sagemaker-huggingface-inference-toolkit#-user-defined-codemodules).
But I agree with you since you already into trouble we should make it more clear.

> 
> The Hugging Face Inference Toolkit allows user to override the default methods of the HuggingFaceHandlerService. Therefor the need to create a named code/ with a inference.py file in it. For example:
> 
> model.tar.gz/
> |- pytroch_model.bin
> |- ....
> |- code/
>   |- inference.py
>   |- requirements.txt 
> In this example, pytroch_model.bin is the model file saved from training, inference.py is the custom inference module, and requirements.txt is a requirements file to add additional dependencies. The custom module can override the following methods:

**Comment by la-cruche** [comment]
yes, what I meant is that the doc didn't say "don't create folders, have every file in the archive without any folder" right?

**Comment by philschmid** [comment]
added this to the documentation. 
### Model artificat structure `model.tar.gz`

The `model.tar.gz` contains all required files to run your model including your model file either `pytorch_model.bin`, `tf_model.h5`, `tokenizer.json` , `tokenizer_config.json` etc. All model artifacts need to be directly in the archive without folder hierarchy. 

examples for PyTorch:

```bash
model.tar.gz/
|- pytroch_model.bin
|- vocab.txt
|- tokenizer_config.json
|- config.json
|- special_tokens_map.json
```

**Comment by la-cruche** [comment]
nice! but we agree that with custom `model_fn` the archive structure can be anything right? people would be responsible to write code that can parse it

**Comment by philschmid** [comment]
Yes
