### ISSUE TITLE
[DOCS] List of available HF_TASK and default inference scripts

### ISSUE THREAD

**Issue by austinmw** [aws/sagemaker-huggingface-inference-toolkit#90]
Hi, if for example I deploy the following:

```python
from sagemaker.huggingface import HuggingFaceModel

# Hub Model configuration. https://huggingface.co/models
hub = {
  'HF_MODEL_ID':'distilbert-base-uncased-distilled-squad', # model_id from hf.co/models
  'HF_TASK':'question-answering' # NLP task you want to use for predictions
}

# create Hugging Face Model Class
huggingface_model = HuggingFaceModel(
   env=hub,
   role=role, # iam role with permissions to create an Endpoint
   transformers_version="4.26", # transformers version used
   pytorch_version="1.13", # pytorch version used
   py_version="py39", # python version of the DLC
)
```

Where can I find the list of available `HF_TASK`, and the default inference script for each task (if I don't provide a custom one)?

----

I ask because I'd like to deploy a text embedding model, which I believe is under the task `feature-extraction`, but I'm not quite sure, and also don't know what the inference script looks like for this. 

For more context, I've deployed the `hkunlp/instructor-large` model with a custom inference script, but am wondering if that is needed or if I could have deployed it without a custom script.

**Comment by philschmid** [comment]
The snippet always use the task the model is fine-tuned on. The `distilbert-base-uncased-distilled-squad` cannot be used for any other task. 
For your example to run `instructor` models you need their pypi package.

**Comment by austinmw** [comment]
Do I need custom inference code to run the instructor model? I got it to work using the below code in the style of your `sagemaker/17_custom_inference_script/sagemaker-notebook.ipynb` example:

```python
from InstructorEmbedding import INSTRUCTOR
import torch
import torch.nn.functional as F


def model_fn(model_dir):
  model = INSTRUCTOR(
    model_name_or_path=model_dir,
    #device: Optional[str] = None,
    #cache_folder: Optional[str] = None,
    #use_auth_token: Union[bool, str, NoneType] = None,
  )
  print(f"model: {model}")
  print(f"model.device: {model.device}")
  return model


def predict_fn(data, model):
    # Get instruction
    instruction = data.pop("instruction", "Represent the query for retrieval: ")
    print(f"instruction: {instruction}")

    # Get sentences
    sentences = data.pop("sentences")
    print(f"sentences: {sentences}")

    # Pair instruction with each input sentence and encode
    with torch.no_grad():
        embeddings = model.encode([[instruction, sentence] for sentence in sentences])
    print(f"embeddings.shape: {embeddings.shape}")

    # Return dictonary, which will be json serializable
    return {"vectors": embeddings.tolist()}
```


However I'm curious if I needed to do that, or if there's a way to deploy it without custom code?

**Comment by austinmw** [comment]
Thanks
